### ISSUE TITLE
Broken links in __init__.py

### ISSUE THREAD

**Issue by untitaker** [avelino/liquidluck#120]
http://lab.lepture.com/liquidluck/ in `__init__` 404s. It should redirect (cc @lepture), but also the link should be changed to the new location.

**Comment by lepture** [comment]
Fixed.

**Comment by untitaker** [comment]
Thank you, I will keep this issue open for fixing links elsewhere.

**Comment by untitaker** [comment]
@avelino There are still links scattered throughout the codebase. Should I make a PR?

**Comment by avelino** [comment]
Can do PR. pls

**Comment by untitaker** [comment]
@avelino See https://github.com/avelino/liquidluck/pull/122
